---
calico_version: 0.19.0

calico_image: calico/node
calico_image_tag: v{{ calico_version }}

etcd_service_name: etcd.service.{{ consul_dns_domain }}
etcd_client_port: 2379

calico_etcdaddr: "{{ private_ipv4 }}:{{ etcd_client_port }}"

calico_network: 192.168.0.0/16

calico_profile: dev
